CREATE TABLE IF NOT EXISTS PRODUCTS (
    ID INT NOT NULL,
    TITLE VARCHAR(255) NULL,
    PRICE DECIMAL(20,2) NULL,
    DESCRIPTION VARCHAR(5000) NULL,
    CATEGORY VARCHAR(255) NULL,
	IMAGE VARCHAR(255) NULL,
	RATING VARCHAR(5000) NULL,
    PROCESS_DATE DATE NOT NULL,
    LOAD_DATE TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);